apiVersion: v1
kind: Service
metadata:
  name: luis-enrique-17-service
  namespace: luis-enrique-17-namespace
spec:
  type: NodePort
  ports:
  - port: 30017
    targetPort: 8080
    nodePort: 30017
  selector:
    app: luis-enrique-17-deployment