apiVersion: v1
kind: Secret
metadata:
  name: luis-enrique-17-secret
  namespace: luis-enrique-17-namespace
type: Opaque
data:
  # OJO: Los valores a la derecha son ejemplos en Base64. 
  # Tienes que cambiarlos por tus llaves reales convertidas a Base64.
  SPRING_DATA_MONGODB_URI: bW9uZ29kYitzcnY6Ly9sdWlzOlRVX1BBU1NXT1JEQGNsdXN0ZXIwLnltYnJrN3MubW9uZ29kYi5uZXQvVFVfQkQ=
  API_GEMINI_KEY: dHVfY2xhdmVfZGVfZ2VtaW5pX2FxdWk=
  API_HUGGINGFACE_KEY: dHVfY2xhdmVfZGVfaHVnZ2luZ2ZhY2VfYXF1aQ==