apiVersion: v1
kind: Service
metadata:
  name: api-ia-service-17
  namespace: ia-project-ns-17
spec:
  type: NodePort
  selector:
    app: api-ia-spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080