apiVersion: apps/v1
kind: Deployment
metadata:
  name: luis-enrique-17-deployment
  namespace: luis-enrique-17-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: luis-enrique-17-deployment
  template:
    metadata:
      labels:
        app: luis-enrique-17-deployment
    spec:
      containers:
      - name: luis-enrique-17-container
        image: luisenrique1/api-ia-mongodb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: luis-enrique-17-secret